{
 "title": "Weather station",
 "description": "Atmospheric pressure, indoor/outdoor temperatures, humidity, CO2 concentration, wind speed and rainfall.",
 "tags": [
  "netatmo",
  "weather"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "InfluxDB-netatmo" },
   { "name": "devices", "label": "Devices", "query": "Maison" },
   { "name": "modules", "label": "Temperature modules", "query": "Salon,Terrasse,Chambre" },
   { "name": "windGauge", "label": "Wind module", "query": "Anémomètre" },
   { "name": "rainGauge", "label": "Wind module", "query": "Pluviomètre" },
   { "name": "mainModule", "label": "Main module", "query": "Salon" }
  ]
 },
 "panels": [
  {
   "title": "Atmospheric pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval*4" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$devices-$mainModule/",
     "query": "SELECT mean(\"humidity\") AS \"humidity\", max(\"temperature\") AS \"max temperature\", min(\"temperature\") AS \"min temperature\" FROM \"Maison-Terrasse\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max pressure" ], "type": "alias" }
      ],
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min pressure" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval*4" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$devices-$windGauge/",
     "query": "SELECT mean(\"GustStrength\") AS \"Max Strength\", mean(\"WindStrength\") AS \"Strength\", mean(\"GustAngle\") AS \"Max Angle\" FROM \"Maison-Anémomètre\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "GustStrength" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "gust" ], "type": "alias" }
      ],
      [
       { "params": [ "WindStrength" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "average speed" ], "type": "alias" }
      ],
      [
       { "params": [ "GustAngle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "direction" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indoor noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval*4" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$devices-$mainModule/",
     "query": "SELECT mean(\"humidity\") AS \"humidity\", max(\"temperature\") AS \"max temperature\", min(\"temperature\") AS \"min temperature\" FROM \"Maison-Terrasse\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "noise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "noise" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval*4" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$devices-$rainGauge/",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "rainfall" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature ($devices - $modules)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "repeat": "modules",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval*4" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$devices-$modules/",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min temperature" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2 concentration / humidity ($devices - $modules)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "repeat": "modules",
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval*4" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$devices-$modules/",
     "select": [
      [
       { "params": [ "Co2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max CO2" ], "type": "alias" }
      ],
      [
       { "params": [ "Co2" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min CO2" ], "type": "alias" }
      ],
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "humidity" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}